### ISSUE TITLE
commissioner buttons are too easily clicked, scary

### ISSUE THREAD

**Issue by kprevas** [mayhew3/DraftTower#112]
Mayhew pointed out that "reset draft" was really close to "pick".  We should throw these into a popup or something so that they can't be clicked accidentally.

**Comment by mayhew3** [comment]
Yeah, maybe a two-step process of like "Show Commish Tools" and then click the one you want. It might also be nice if the buttons remained stationary after you click "Pick", because when the player name disappears, they shift upward. Maybe have a blank placeholder or grey "No Player Selected"?
