### ISSUE TITLE
Favorite Players: more distinct visually?

### ISSUE THREAD

**Issue by mayhew3** [mayhew3/DraftTower#139]
Any way we could highlight the whole row a different color if the player is starred? Maybe a light purple?

**Comment by mayhew3** [comment]
- Does AWS need a redeploy?
- When you select a row, can the selection color take precedence over the favorite?

**Comment by kprevas** [comment]
AWS seems fine for me?

Fixing the other issue now.

**Comment by mayhew3** [comment]
Weird. Yeah, I see the highlighting now.
